### ISSUE TITLE
Build Issues with Rebar3 on MacOS 10.13.6

### ISSUE THREAD

**Issue by gokulsan** [aeternity/aesophia_cli#52]
Hello Team,

I am facing the following issues while I am trying to build the aesophia_cli tools on my MacOS 10.13.6 environment as per the steps mentioned in the README. Could you please help to resolve this issue. Looking forward to hearing from you! 

Gokuls-MacBook-Air:aesophia_cli gokulalex$ ./rebar3 escriptize
===> Verifying dependencies...
=WARNING REPORT==== 25-Dec-2021::13:22:31.401915 ===
Description: "Authenticity is not established by certificate path validation"
     Reason: "Option {verify, verify_peer} and cacertfile/cacerts is missing"

===> Fetching aeserialization ({git,
                                       "https://github.com/aeternity/aeserialization.git",
                                       {ref,
                                        "58e34ae7b5abfcc54f505ea8d57183d04f67120e"}})
===> Fetching aesophia ({git,
                                   "https://github.com/aeternity/aesophia.git",
                                   {ref,
                                       "5ad5270e381f6e810d7b8b5cdc168d283e7a90bb"}})
===> Fetching eblake2 ({pkg,<<"eblake2">>,<<"1.0.0">>})
===> Downloaded package, caching at /Users/gokulalex/.cache/rebar3/hex/hexpm/packages/eblake2-1.0.0.tar
escript: exception error: undefined function erlang:get_stacktrace/0
  in function  rebar3:main/1 (/home/dev/work/rebar3/src/rebar3.erl, line 72)
  in call from escript:run/2 (escript.erl, line 750)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1 
  in call from init:do_boot/3

**Comment by hanssv** [comment]
It looks like you are using Erlang OTP-24; `aesophia_cli` is not supporting that yet, it is in the pipeline.

**Comment by ghallak** [comment]
Moving this issue to #55
