### ISSUE TITLE
Compilation Issue in Ubuntu 21.04

### ISSUE THREAD

**Issue by gokulsan** [aeternity/aesophia_cli#53]
Hi Aeternity Team,

I was trying to build the aesophia_cli package on Ubuntu 21.04. I am getting the following compilation error. Could you please share your guidance to address this issue. Looking forward to hearing from you.

/Apps/ae-apps/aesophia_cli$ rebar3 escriptize
===> Verifying dependencies...
===> Fetching aeserialization (from {git,"https://github.com/aeternity/aeserialization.git",
                           {ref,"58e34ae7b5abfcc54f505ea8d57183d04f67120e"}})
===> Fetching aesophia (from {git,"https://github.com/aeternity/aesophia.git",
                    {ref,"5ad5270e381f6e810d7b8b5cdc168d283e7a90bb"}})
===> Fetching eblake2 v1.0.0
===> Downloaded package, caching at /home/semiott/.cache/rebar3/hex/hexpm/packages/eblake2-1.0.0.tar
===> Fetching rebar3_hex v6.11.9
===> Downloaded package, caching at /home/semiott/.cache/rebar3/hex/hexpm/packages/rebar3_hex-6.11.9.tar
===> Fetching hex_core v0.8.4
===> Downloaded package, caching at /home/semiott/.cache/rebar3/hex/hexpm/packages/hex_core-0.8.4.tar
===> Fetching verl v1.0.2
===> Downloaded package, caching at /home/semiott/.cache/rebar3/hex/hexpm/packages/verl-1.0.2.tar
===> Compiling verl
===> Compiling hex_core
===> Compiling rebar3_hex
===> Fetching aebytecode (from {git,"https://github.com/aeternity/aebytecode.git",
                      {ref,"05dfd7ffc7fb1e07ecc0b1e516da571f56d7dc8f"}})
===> Fetching base58 (from {git,"https://github.com/aeternity/erl-base58.git",
                  {ref,"60a335668a60328a29f9731b67c4a0e9e3d50ab6"}})
===> Fetching enacl (from {git,"https://github.com/aeternity/enacl.git",
                 {ref,"26180f42c0b3a450905d2efd8bc7fd5fd9cece75"}})
===> Fetching pc v1.13.0
===> Downloaded package, caching at /home/semiott/.cache/rebar3/hex/hexpm/packages/pc-1.13.0.tar
===> Compiling pc
===> Fetching getopt v1.0.1
===> Downloaded package, caching at /home/semiott/.cache/rebar3/hex/hexpm/packages/getopt-1.0.1.tar
===> Fetching jsx (from {git,"https://github.com/talentdeficit/jsx.git",
               {ref,"3074d4865b3385a050badf7828ad31490d860df5"}})
===> Compiling jsx
===> Compiling getopt
===> Compiling eblake2
===> Compiling enacl
===> Compiling /home/semiott/Apps/ae-apps/aesophia_cli/c_src/enacl_nif.c
===> /home/semiott/Apps/ae-apps/aesophia_cli/c_src/enacl_nif.c:5:10: fatal error: sodium.h: No such file or directory
    5 | #include <sodium.h>
      |          ^~~~~~~~~~
compilation terminated.

**Comment by hanssv** [comment]
Either you have not installed `libsodium` libraries or you failed to point your compiler to its location.
https://forum.aeternity.com/t/rebar3-compilation-issue-in-ubuntu-21-04/10339
