### ISSUE TITLE
Multiline error messages

### ISSUE THREAD

**Issue by dincho** [aeternity/aesophia_cli#54]
I wonder what's the reason to include newline in the compiler error output? This is a bit harsh to parse by other tools and would be even more ambiguous if multiple error messages are printed.

**Comment by ghallak** [comment]
I was trying to solve a similar issue for `aesophia_http` here https://github.com/aeternity/aesophia/pull/362.

I haven't checked how the output looks like for `aesophia_cli` but I think I can fix that in the same PR.

**Comment by ghallak** [comment]
@dincho Hasn't this been solved already?

**Comment by dincho** [comment]
I think so. We tested a version with @hanssv IIRC

**Comment by dincho** [comment]
yep, it's https://github.com/aeternity/aesophia_cli/pull/56
