### ISSUE TITLE
Be a good unix citizen

### ISSUE THREAD

**Issue by dincho** [aeternity/aesophia_cli#59]
Currently the CLI does not care much about `stderr` and `stdout` it seems as errors and warnings are dumped to stdout as well. They should go to `stderr` instead and the bytecode should go to `stdout` without any formatting (i.e. now it also includes `Bytecode:` prefix.

Of course the extra formatting can be removed only if options combinations are not supported (i.e. adding --pp_asm also dump the FASM).

`--create_json_aci` is a good example how it *should* work, by dumping only ACI

Please note the exit codes as well, warnings should not lead to error exit code (which is the case right now).

**Comment by ghallak** [comment]
>Please note the exit codes as well, warnings should not lead to error exit code (which is the case right now).

@dincho As I'm checking, I'm getting 0 exit code when there are warnings (unless I use `--error_warning`). Can you tell how did you manage to get an error exit code when the input file has warnings?

**Comment by dincho** [comment]
> @dincho As I'm checking, I'm getting 0 exit code when there are warnings (unless I use `--error_warning`). Can you tell how did you manage to get an error exit code when the input file has warnings?

I don't remember how I reproduced it, perhaps testing some of the PRs. I don't have a master version as the CI artefact expired.

**Comment by ghallak** [comment]
I'm unable to reproduce an exit error beside 0 when the compiled file has warnings (but doesn't have errors), if you manage to reproduce that, you can reopen the issue (or open a new one).
