### ISSUE TITLE
Space chars change compiled bytecode

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aesophia_cli#73]
I've noticed that if I add or remove space chars, the compiled bytecode insignificantly changes. From my perspective, these space chars don't change the contract semantics so the bytecode should be the same. Does it happen because the bytecode contains the hash of the source code? Can it be used somehow?

The current behavior looks odd because if I add space chars to an included file then the bytecode remains the same.

**Comment by dincho** [comment]
The commonly known as bytecode piece of code is actually a serialized contract object that indeed includes the source hash together with the actual bytecode and some other properties.

**Comment by hanssv** [comment]
Yes, I think this is a documentation issue - the result of calling the compiler is a complete object that can go into the ContractCreateTx. It is a structured object containing among other things the actual contract byte code, but also the hash of the source code, the compiler version and whether or not the contract is payable...

**Comment by davidyuk** [comment]
Got it. But shouldn't included files be hashed as well?
